package com.wahyuhw.mealrecipes.domain.recipe.model

import android.os.Parcelable
import com.wahyuhw.mealrecipes.utils.emptyString
import kotlinx.parcelize.Parcelize

@Parcelize
data class RecipeDetail(
	val idMeal: String = emptyString(),
	val strMeal: String = emptyString(),
	val strDrinkAlternate: String = emptyString(),
	val strCategory: String = emptyString(),
	val strArea: String = emptyString(),
	val strInstructions: String = emptyString(),
	val strMealThumb: String = emptyString(),
	val strTags: String = emptyString(),
	val strYoutube: String = emptyString(),
	val strIngredient1: String = emptyString(),
	val strIngredient2: String = emptyString(),
	val strIngredient3: String = emptyString(),
	val strIngredient4: String = emptyString(),
	val strIngredient5: String = emptyString(),
	val strIngredient6: String = emptyString(),
	val strIngredient7: String = emptyString(),
	val strIngredient8: String = emptyString(),
	val strIngredient9: String = emptyString(),
	val strIngredient10: String = emptyString(),
	val strIngredient11: String = emptyString(),
	val strIngredient12: String = emptyString(),
	val strIngredient13: String = emptyString(),
	val strIngredient14: String = emptyString(),
	val strIngredient15: String = emptyString(),
	val strIngredient16: String = emptyString(),
	val strIngredient17: String = emptyString(),
	val strIngredient18: String = emptyString(),
	val strIngredient19: String = emptyString(),
	val strIngredient20: String = emptyString(),
	val strMeasure1: String = emptyString(),
	val strMeasure2: String = emptyString(),
	val strMeasure3: String = emptyString(),
	val strMeasure4: String = emptyString(),
	val strMeasure5: String = emptyString(),
	val strMeasure6: String = emptyString(),
	val strMeasure7: String = emptyString(),
	val strMeasure8: String = emptyString(),
	val strMeasure9: String = emptyString(),
	val strMeasure10: String = emptyString(),
	val strMeasure11: String = emptyString(),
	val strMeasure12: String = emptyString(),
	val strMeasure13: String = emptyString(),
	val strMeasure14: String = emptyString(),
	val strMeasure15: String = emptyString(),
	val strMeasure16: String = emptyString(),
	val strMeasure17: String = emptyString(),
	val strMeasure18: String = emptyString(),
	val strMeasure19: String = emptyString(),
	val strMeasure20: String = emptyString(),
	val strSource: String = emptyString(),
	val strImageSource: String = emptyString(),
	val strCreativeCommonsConfirmed: String = emptyString(),
	val dateModified: String = emptyString()
): Parcelable